Update code in documentation
When I tried to use a set, I got the following error: 

```
ValueError: asn1crypto.core.BitString._map has not been defined
    while constructing asn1crypto.core.BitString
```